"""Volition type definitions: Goal, Intention, and related enums."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class GoalPriority(Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class GoalStatus(Enum):
    PENDING = "pending"
    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


@dataclass
class Goal:
    """A goal generated by the Volition engine from C2 metacognitive results."""

    goal_id: str
    description: str
    priority: GoalPriority
    source: str
    status: GoalStatus = GoalStatus.PENDING
    parent_goal_id: Optional[str] = None
    progress: float = 0.0
    created_at: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "goal_id": self.goal_id,
            "description": self.description,
            "priority": self.priority.value,
            "source": self.source,
            "status": self.status.value,
            "parent_goal_id": self.parent_goal_id,
            "progress": self.progress,
            "created_at": self.created_at,
            "metadata": self.metadata,
        }


@dataclass
class Intention:
    """A concrete intention to act, selected from an active goal."""

    intention_id: str
    goal_id: str
    action: str
    confidence: float
    priority: GoalPriority
    created_at: str = ""

    def to_dict(self) -> dict:
        return {
            "intention_id": self.intention_id,
            "goal_id": self.goal_id,
            "action": self.action,
            "confidence": self.confidence,
            "priority": self.priority.value,
            "created_at": self.created_at,
        }


@dataclass
class IntentionConflict:
    """A conflict detected between two intentions in the buffer."""

    intention1: Intention
    intention2: Intention
    conflict_type: str
    description: str
    severity: float

    def to_dict(self) -> dict:
        return {
            "intention1": self.intention1.to_dict(),
            "intention2": self.intention2.to_dict(),
            "conflict_type": self.conflict_type,
            "description": self.description,
            "severity": self.severity,
        }


__all__ = [
    "Goal",
    "GoalPriority",
    "GoalStatus",
    "Intention",
    "IntentionConflict",
]
